POST https://management-system-2d8df.web.app/api/auth/login
Content-Type: application/json

{
  "username": "manish",
  "password": "123456789"
}

# ###

POST http://localhost:3000/api/auth/signup
Content-Type:application/json

{
    "username":"RakeshGupta",
    "email":"rakesh3239@gmail.com",
    "password":"123456"
}

# GET http://localhost:3000/api/task/alltask
# Content-Type:application/json

# {
#     "username":"Manish3239",
#     "email":"manish3239@gmail.com",
#     "password":"123456"
# }

# POST http://localhost:3000/api/task/completeTask
# Content-Type:application/json
# {
#   "id": "67587c7004cfd8e312b3024b", 
# }

GET http://localhost:3000/api/admin/users
Content-Type:application/json
{
  "name": "manish", 
}
